spring:
  datasource:
    url: jdbc:sqlserver://ALPHARLA.ngintad.local:1040;databaseName=car-db
    username: carsample
    password: '{cipher}052d52623f96af5ee495551601eb439dc543685338d5c524fe2efaa0070baac8'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka